### PR TITLE
small updates

### PR DESCRIPTION
**Pull request by stevenpkg**

### CODE REVIEW

**Comment by germanattanasio** [comment]
@stevenpkg Always make sure that someone else merges your Pull Requests. You can assign them to me and I will assign them to you. We need to make sure we do some peer review before changing the public demos

**Comment by stevenpkg** [comment]
@germanattanasio I agree, good practice to review each others changes

**Comment by RobertColquhoun** [comment]
Hi, is it possible that your change to manifest.yml has caused a build error with the public demo?  I'm getting an error when trying to deploy "FAILED
Could not find service my-discovery-service to bind to xxx".  It seems that the service is called "my-discovery-service" in this file but "discovery-service" in pipeline.yml

**Comment by stevenpkg** [comment]
Yes It should be called my-decover-service to be consistent. If this is a problem I can change the name back to my-discovery?
 
 
Regards,
Steve
Steve Green
Watson Conversation System Developer
Phone: 61- 416 179 737
E-mail: stevenpkg@au1.ibm.com
 
 
----- Original message -----From: RobertColquhoun <notifications@github.com>To: watson-developer-cloud/conversation-with-discovery <conversation-with-discovery@noreply.github.com>Cc: Steve Green/Australia/IBM@IBMAU, Mention <mention@noreply.github.com>Subject: Re: [watson-developer-cloud/conversation-with-discovery] small updates (#68)Date: Sat, Mar 11, 2017 7:35 AM 
Hi, is it possible that your change to manifest.yml has caused a build error with the public demo? I'm getting an error when trying to deploy "FAILEDCould not find service my-discovery-service to bind to xxx". It seems that the service is called "my-discovery-service" in this file but "discovery-service" in pipeline.yml

**Pull request merged**
